/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ActionDelay from './model/ActionDelay';
import ActionDelayInput from './model/ActionDelayInput';
import ActionDelayInputProperties from './model/ActionDelayInputProperties';
import ActionDelayInputPropertiesInput from './model/ActionDelayInputPropertiesInput';
import ActionDelayListResponse from './model/ActionDelayListResponse';
import ActionDelayResponse from './model/ActionDelayResponse';
import ActionDeleteResponse from './model/ActionDeleteResponse';
import ActionListResponse from './model/ActionListResponse';
import ActionReboot from './model/ActionReboot';
import ActionRebootResponse from './model/ActionRebootResponse';
import ActionRequest from './model/ActionRequest';
import ActionRequestDelay from './model/ActionRequestDelay';
import ActionRequestDelayInput from './model/ActionRequestDelayInput';
import ActionResponseElement1 from './model/ActionResponseElement1';
import ActionResponseElement1Delay from './model/ActionResponseElement1Delay';
import ActionUpdateRequest from './model/ActionUpdateRequest';
import ActionUpdateRequestDelay from './model/ActionUpdateRequestDelay';
import ActionUpdateResponse from './model/ActionUpdateResponse';
import ActionUpdateResponseDelay from './model/ActionUpdateResponseDelay';
import AuthZError from './model/AuthZError';
import AuthZErrorError from './model/AuthZErrorError';
import BadFormedError from './model/BadFormedError';
import BadFormedErrorError from './model/BadFormedErrorError';
import BaseError from './model/BaseError';
import BaseErrorError from './model/BaseErrorError';
import CollectionListResponse from './model/CollectionListResponse';
import CollectionListResponsePaging from './model/CollectionListResponsePaging';
import CollectionRequest from './model/CollectionRequest';
import CollectionResponse from './model/CollectionResponse';
import CollectionUpdateRequest from './model/CollectionUpdateRequest';
import CollectionUpdateResponse from './model/CollectionUpdateResponse';
import CreateLabel from './model/CreateLabel';
import CreateLabelRelation from './model/CreateLabelRelation';
import CreateLabelResponse from './model/CreateLabelResponse';
import CreateMQTTLabelCredentials from './model/CreateMQTTLabelCredentials';
import CreateMQTTLabelCredentialsResponse from './model/CreateMQTTLabelCredentialsResponse';
import CredentialsError from './model/CredentialsError';
import CredentialsErrorError from './model/CredentialsErrorError';
import CredentialsStudio from './model/CredentialsStudio';
import CredentialsThing from './model/CredentialsThing';
import ErrorResponse from './model/ErrorResponse';
import ErrorResponseError from './model/ErrorResponseError';
import EventHighCPU from './model/EventHighCPU';
import EventHighCPUData from './model/EventHighCPUData';
import EventHighCPUListResponse from './model/EventHighCPUListResponse';
import EventHighCPUResponse from './model/EventHighCPUResponse';
import EventListResponse from './model/EventListResponse';
import EventRequest from './model/EventRequest';
import EventRequestHighCPU from './model/EventRequestHighCPU';
import EventResponse from './model/EventResponse';
import EventResponseHighCPU from './model/EventResponseHighCPU';
import Function from './model/Function';
import FunctionMetrics from './model/FunctionMetrics';
import FunctionOptions from './model/FunctionOptions';
import FunctionStatusEnum from './model/FunctionStatusEnum';
import Functions from './model/Functions';
import FunctionsPaging from './model/FunctionsPaging';
import InfoResponse from './model/InfoResponse';
import LabelDeleteResponse from './model/LabelDeleteResponse';
import LabelListElement1 from './model/LabelListElement1';
import LabelListElementRelations from './model/LabelListElementRelations';
import LabelListResponse from './model/LabelListResponse';
import LabelRelationElement1 from './model/LabelRelationElement1';
import LabeledListItem1 from './model/LabeledListItem1';
import LabeledListResponse from './model/LabeledListResponse';
import ListCredentialsResponse from './model/ListCredentialsResponse';
import LogEntry from './model/LogEntry';
import MQTTAccountActions from './model/MQTTAccountActions';
import MQTTAccountData from './model/MQTTAccountData';
import MQTTAccountEvents from './model/MQTTAccountEvents';
import MQTTAccountPattern1 from './model/MQTTAccountPattern1';
import MQTTAccountPattern2 from './model/MQTTAccountPattern2';
import MQTTAccountPattern3 from './model/MQTTAccountPattern3';
import MQTTAccountProperties from './model/MQTTAccountProperties';
import MQTTLabel from './model/MQTTLabel';
import ModelListResponse from './model/ModelListResponse';
import ModelRequest from './model/ModelRequest';
import ModelResponse from './model/ModelResponse';
import ModelUpdateRequest from './model/ModelUpdateRequest';
import ModelUpdateResponse from './model/ModelUpdateResponse';
import ModelVersionListResponse from './model/ModelVersionListResponse';
import ModelVersionRequest from './model/ModelVersionRequest';
import ModelVersionRequestProperties from './model/ModelVersionRequestProperties';
import ModelVersionResponse from './model/ModelVersionResponse';
import ModelVersionResponseAllOf from './model/ModelVersionResponseAllOf';
import Properties from './model/Properties';
import Property from './model/Property';
import PropertyCPU from './model/PropertyCPU';
import PropertyCPUResponse from './model/PropertyCPUResponse';
import PropertyCPUResponseLinks from './model/PropertyCPUResponseLinks';
import PropertyDisk from './model/PropertyDisk';
import PropertyDiskResponse from './model/PropertyDiskResponse';
import PropertyMemory from './model/PropertyMemory';
import PropertyMemoryResponse from './model/PropertyMemoryResponse';
import RelationError from './model/RelationError';
import RelationErrorError from './model/RelationErrorError';
import Secret from './model/Secret';
import ShowCredentialsThingResponse from './model/ShowCredentialsThingResponse';
import ShowMQTTLabelResponse from './model/ShowMQTTLabelResponse';
import SourceCode from './model/SourceCode';
import ThingCreateResponse from './model/ThingCreateResponse';
import ThingCreateResponseCredentials from './model/ThingCreateResponseCredentials';
import ThingCreateResponseCredentialsHttp from './model/ThingCreateResponseCredentialsHttp';
import ThingCreateResponseCredentialsMqtt from './model/ThingCreateResponseCredentialsMqtt';
import ThingCreateResponseCredentialsMqttData from './model/ThingCreateResponseCredentialsMqttData';
import ThingCreateResponseCredentialsMqttThing from './model/ThingCreateResponseCredentialsMqttThing';
import ThingCreateResponseLinks from './model/ThingCreateResponseLinks';
import ThingDeleteResponse from './model/ThingDeleteResponse';
import ThingDeleteResponseErrorClusterBackend from './model/ThingDeleteResponseErrorClusterBackend';
import ThingListResponse from './model/ThingListResponse';
import ThingRequest from './model/ThingRequest';
import ThingResponse from './model/ThingResponse';
import ThingStatusListResponse from './model/ThingStatusListResponse';
import ThingStatusResponse from './model/ThingStatusResponse';
import ThingUpdateRequest from './model/ThingUpdateRequest';
import ThingUpdateResponse from './model/ThingUpdateResponse';
import TokenResponse from './model/TokenResponse';
import Trigger from './model/Trigger';
import TriggerMqttConfig from './model/TriggerMqttConfig';
import TriggerRabbitMQConfig from './model/TriggerRabbitMQConfig';
import TriggerStatusEnum from './model/TriggerStatusEnum';
import TriggerTypeEnum from './model/TriggerTypeEnum';
import Triggers from './model/Triggers';
import UpdateMQTTCredentials from './model/UpdateMQTTCredentials';
import UpdateMQTTCredentialsResponse from './model/UpdateMQTTCredentialsResponse';
import UpdateMQTTLabelCredentials from './model/UpdateMQTTLabelCredentials';
import UpdateMQTTPassword from './model/UpdateMQTTPassword';
import ActionsApi from './api/ActionsApi';
import CollectionsApi from './api/CollectionsApi';
import EventsApi from './api/EventsApi';
import FunctionsApi from './api/FunctionsApi';
import ItemsApi from './api/ItemsApi';
import LabelApi from './api/LabelApi';
import LabeledEntitiesApi from './api/LabeledEntitiesApi';
import MQTTCredentialsApi from './api/MQTTCredentialsApi';
import MQTTLabelsApi from './api/MQTTLabelsApi';
import MQTTThingsApi from './api/MQTTThingsApi';
import MQTTUsernameApi from './api/MQTTUsernameApi';
import ModelVersionsApi from './api/ModelVersionsApi';
import ModelsApi from './api/ModelsApi';
import OAuthApi from './api/OAuthApi';
import PropertiesApi from './api/PropertiesApi';
import ThingsApi from './api/ThingsApi';
import TriggersApi from './api/TriggersApi';


/**
* MQTT_OpenAPI_endpoints___OpenAPI_3_0.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MqttApiReference = require('index'); // See note below*.
* var xxxSvc = new MqttApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MqttApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MqttApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MqttApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ActionDelay model constructor.
     * @property {module:model/ActionDelay}
     */
    ActionDelay,

    /**
     * The ActionDelayInput model constructor.
     * @property {module:model/ActionDelayInput}
     */
    ActionDelayInput,

    /**
     * The ActionDelayInputProperties model constructor.
     * @property {module:model/ActionDelayInputProperties}
     */
    ActionDelayInputProperties,

    /**
     * The ActionDelayInputPropertiesInput model constructor.
     * @property {module:model/ActionDelayInputPropertiesInput}
     */
    ActionDelayInputPropertiesInput,

    /**
     * The ActionDelayListResponse model constructor.
     * @property {module:model/ActionDelayListResponse}
     */
    ActionDelayListResponse,

    /**
     * The ActionDelayResponse model constructor.
     * @property {module:model/ActionDelayResponse}
     */
    ActionDelayResponse,

    /**
     * The ActionDeleteResponse model constructor.
     * @property {module:model/ActionDeleteResponse}
     */
    ActionDeleteResponse,

    /**
     * The ActionListResponse model constructor.
     * @property {module:model/ActionListResponse}
     */
    ActionListResponse,

    /**
     * The ActionReboot model constructor.
     * @property {module:model/ActionReboot}
     */
    ActionReboot,

    /**
     * The ActionRebootResponse model constructor.
     * @property {module:model/ActionRebootResponse}
     */
    ActionRebootResponse,

    /**
     * The ActionRequest model constructor.
     * @property {module:model/ActionRequest}
     */
    ActionRequest,

    /**
     * The ActionRequestDelay model constructor.
     * @property {module:model/ActionRequestDelay}
     */
    ActionRequestDelay,

    /**
     * The ActionRequestDelayInput model constructor.
     * @property {module:model/ActionRequestDelayInput}
     */
    ActionRequestDelayInput,

    /**
     * The ActionResponseElement1 model constructor.
     * @property {module:model/ActionResponseElement1}
     */
    ActionResponseElement1,

    /**
     * The ActionResponseElement1Delay model constructor.
     * @property {module:model/ActionResponseElement1Delay}
     */
    ActionResponseElement1Delay,

    /**
     * The ActionUpdateRequest model constructor.
     * @property {module:model/ActionUpdateRequest}
     */
    ActionUpdateRequest,

    /**
     * The ActionUpdateRequestDelay model constructor.
     * @property {module:model/ActionUpdateRequestDelay}
     */
    ActionUpdateRequestDelay,

    /**
     * The ActionUpdateResponse model constructor.
     * @property {module:model/ActionUpdateResponse}
     */
    ActionUpdateResponse,

    /**
     * The ActionUpdateResponseDelay model constructor.
     * @property {module:model/ActionUpdateResponseDelay}
     */
    ActionUpdateResponseDelay,

    /**
     * The AuthZError model constructor.
     * @property {module:model/AuthZError}
     */
    AuthZError,

    /**
     * The AuthZErrorError model constructor.
     * @property {module:model/AuthZErrorError}
     */
    AuthZErrorError,

    /**
     * The BadFormedError model constructor.
     * @property {module:model/BadFormedError}
     */
    BadFormedError,

    /**
     * The BadFormedErrorError model constructor.
     * @property {module:model/BadFormedErrorError}
     */
    BadFormedErrorError,

    /**
     * The BaseError model constructor.
     * @property {module:model/BaseError}
     */
    BaseError,

    /**
     * The BaseErrorError model constructor.
     * @property {module:model/BaseErrorError}
     */
    BaseErrorError,

    /**
     * The CollectionListResponse model constructor.
     * @property {module:model/CollectionListResponse}
     */
    CollectionListResponse,

    /**
     * The CollectionListResponsePaging model constructor.
     * @property {module:model/CollectionListResponsePaging}
     */
    CollectionListResponsePaging,

    /**
     * The CollectionRequest model constructor.
     * @property {module:model/CollectionRequest}
     */
    CollectionRequest,

    /**
     * The CollectionResponse model constructor.
     * @property {module:model/CollectionResponse}
     */
    CollectionResponse,

    /**
     * The CollectionUpdateRequest model constructor.
     * @property {module:model/CollectionUpdateRequest}
     */
    CollectionUpdateRequest,

    /**
     * The CollectionUpdateResponse model constructor.
     * @property {module:model/CollectionUpdateResponse}
     */
    CollectionUpdateResponse,

    /**
     * The CreateLabel model constructor.
     * @property {module:model/CreateLabel}
     */
    CreateLabel,

    /**
     * The CreateLabelRelation model constructor.
     * @property {module:model/CreateLabelRelation}
     */
    CreateLabelRelation,

    /**
     * The CreateLabelResponse model constructor.
     * @property {module:model/CreateLabelResponse}
     */
    CreateLabelResponse,

    /**
     * The CreateMQTTLabelCredentials model constructor.
     * @property {module:model/CreateMQTTLabelCredentials}
     */
    CreateMQTTLabelCredentials,

    /**
     * The CreateMQTTLabelCredentialsResponse model constructor.
     * @property {module:model/CreateMQTTLabelCredentialsResponse}
     */
    CreateMQTTLabelCredentialsResponse,

    /**
     * The CredentialsError model constructor.
     * @property {module:model/CredentialsError}
     */
    CredentialsError,

    /**
     * The CredentialsErrorError model constructor.
     * @property {module:model/CredentialsErrorError}
     */
    CredentialsErrorError,

    /**
     * The CredentialsStudio model constructor.
     * @property {module:model/CredentialsStudio}
     */
    CredentialsStudio,

    /**
     * The CredentialsThing model constructor.
     * @property {module:model/CredentialsThing}
     */
    CredentialsThing,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ErrorResponseError model constructor.
     * @property {module:model/ErrorResponseError}
     */
    ErrorResponseError,

    /**
     * The EventHighCPU model constructor.
     * @property {module:model/EventHighCPU}
     */
    EventHighCPU,

    /**
     * The EventHighCPUData model constructor.
     * @property {module:model/EventHighCPUData}
     */
    EventHighCPUData,

    /**
     * The EventHighCPUListResponse model constructor.
     * @property {module:model/EventHighCPUListResponse}
     */
    EventHighCPUListResponse,

    /**
     * The EventHighCPUResponse model constructor.
     * @property {module:model/EventHighCPUResponse}
     */
    EventHighCPUResponse,

    /**
     * The EventListResponse model constructor.
     * @property {module:model/EventListResponse}
     */
    EventListResponse,

    /**
     * The EventRequest model constructor.
     * @property {module:model/EventRequest}
     */
    EventRequest,

    /**
     * The EventRequestHighCPU model constructor.
     * @property {module:model/EventRequestHighCPU}
     */
    EventRequestHighCPU,

    /**
     * The EventResponse model constructor.
     * @property {module:model/EventResponse}
     */
    EventResponse,

    /**
     * The EventResponseHighCPU model constructor.
     * @property {module:model/EventResponseHighCPU}
     */
    EventResponseHighCPU,

    /**
     * The Function model constructor.
     * @property {module:model/Function}
     */
    Function,

    /**
     * The FunctionMetrics model constructor.
     * @property {module:model/FunctionMetrics}
     */
    FunctionMetrics,

    /**
     * The FunctionOptions model constructor.
     * @property {module:model/FunctionOptions}
     */
    FunctionOptions,

    /**
     * The FunctionStatusEnum model constructor.
     * @property {module:model/FunctionStatusEnum}
     */
    FunctionStatusEnum,

    /**
     * The Functions model constructor.
     * @property {module:model/Functions}
     */
    Functions,

    /**
     * The FunctionsPaging model constructor.
     * @property {module:model/FunctionsPaging}
     */
    FunctionsPaging,

    /**
     * The InfoResponse model constructor.
     * @property {module:model/InfoResponse}
     */
    InfoResponse,

    /**
     * The LabelDeleteResponse model constructor.
     * @property {module:model/LabelDeleteResponse}
     */
    LabelDeleteResponse,

    /**
     * The LabelListElement1 model constructor.
     * @property {module:model/LabelListElement1}
     */
    LabelListElement1,

    /**
     * The LabelListElementRelations model constructor.
     * @property {module:model/LabelListElementRelations}
     */
    LabelListElementRelations,

    /**
     * The LabelListResponse model constructor.
     * @property {module:model/LabelListResponse}
     */
    LabelListResponse,

    /**
     * The LabelRelationElement1 model constructor.
     * @property {module:model/LabelRelationElement1}
     */
    LabelRelationElement1,

    /**
     * The LabeledListItem1 model constructor.
     * @property {module:model/LabeledListItem1}
     */
    LabeledListItem1,

    /**
     * The LabeledListResponse model constructor.
     * @property {module:model/LabeledListResponse}
     */
    LabeledListResponse,

    /**
     * The ListCredentialsResponse model constructor.
     * @property {module:model/ListCredentialsResponse}
     */
    ListCredentialsResponse,

    /**
     * The LogEntry model constructor.
     * @property {module:model/LogEntry}
     */
    LogEntry,

    /**
     * The MQTTAccountActions model constructor.
     * @property {module:model/MQTTAccountActions}
     */
    MQTTAccountActions,

    /**
     * The MQTTAccountData model constructor.
     * @property {module:model/MQTTAccountData}
     */
    MQTTAccountData,

    /**
     * The MQTTAccountEvents model constructor.
     * @property {module:model/MQTTAccountEvents}
     */
    MQTTAccountEvents,

    /**
     * The MQTTAccountPattern1 model constructor.
     * @property {module:model/MQTTAccountPattern1}
     */
    MQTTAccountPattern1,

    /**
     * The MQTTAccountPattern2 model constructor.
     * @property {module:model/MQTTAccountPattern2}
     */
    MQTTAccountPattern2,

    /**
     * The MQTTAccountPattern3 model constructor.
     * @property {module:model/MQTTAccountPattern3}
     */
    MQTTAccountPattern3,

    /**
     * The MQTTAccountProperties model constructor.
     * @property {module:model/MQTTAccountProperties}
     */
    MQTTAccountProperties,

    /**
     * The MQTTLabel model constructor.
     * @property {module:model/MQTTLabel}
     */
    MQTTLabel,

    /**
     * The ModelListResponse model constructor.
     * @property {module:model/ModelListResponse}
     */
    ModelListResponse,

    /**
     * The ModelRequest model constructor.
     * @property {module:model/ModelRequest}
     */
    ModelRequest,

    /**
     * The ModelResponse model constructor.
     * @property {module:model/ModelResponse}
     */
    ModelResponse,

    /**
     * The ModelUpdateRequest model constructor.
     * @property {module:model/ModelUpdateRequest}
     */
    ModelUpdateRequest,

    /**
     * The ModelUpdateResponse model constructor.
     * @property {module:model/ModelUpdateResponse}
     */
    ModelUpdateResponse,

    /**
     * The ModelVersionListResponse model constructor.
     * @property {module:model/ModelVersionListResponse}
     */
    ModelVersionListResponse,

    /**
     * The ModelVersionRequest model constructor.
     * @property {module:model/ModelVersionRequest}
     */
    ModelVersionRequest,

    /**
     * The ModelVersionRequestProperties model constructor.
     * @property {module:model/ModelVersionRequestProperties}
     */
    ModelVersionRequestProperties,

    /**
     * The ModelVersionResponse model constructor.
     * @property {module:model/ModelVersionResponse}
     */
    ModelVersionResponse,

    /**
     * The ModelVersionResponseAllOf model constructor.
     * @property {module:model/ModelVersionResponseAllOf}
     */
    ModelVersionResponseAllOf,

    /**
     * The Properties model constructor.
     * @property {module:model/Properties}
     */
    Properties,

    /**
     * The Property model constructor.
     * @property {module:model/Property}
     */
    Property,

    /**
     * The PropertyCPU model constructor.
     * @property {module:model/PropertyCPU}
     */
    PropertyCPU,

    /**
     * The PropertyCPUResponse model constructor.
     * @property {module:model/PropertyCPUResponse}
     */
    PropertyCPUResponse,

    /**
     * The PropertyCPUResponseLinks model constructor.
     * @property {module:model/PropertyCPUResponseLinks}
     */
    PropertyCPUResponseLinks,

    /**
     * The PropertyDisk model constructor.
     * @property {module:model/PropertyDisk}
     */
    PropertyDisk,

    /**
     * The PropertyDiskResponse model constructor.
     * @property {module:model/PropertyDiskResponse}
     */
    PropertyDiskResponse,

    /**
     * The PropertyMemory model constructor.
     * @property {module:model/PropertyMemory}
     */
    PropertyMemory,

    /**
     * The PropertyMemoryResponse model constructor.
     * @property {module:model/PropertyMemoryResponse}
     */
    PropertyMemoryResponse,

    /**
     * The RelationError model constructor.
     * @property {module:model/RelationError}
     */
    RelationError,

    /**
     * The RelationErrorError model constructor.
     * @property {module:model/RelationErrorError}
     */
    RelationErrorError,

    /**
     * The Secret model constructor.
     * @property {module:model/Secret}
     */
    Secret,

    /**
     * The ShowCredentialsThingResponse model constructor.
     * @property {module:model/ShowCredentialsThingResponse}
     */
    ShowCredentialsThingResponse,

    /**
     * The ShowMQTTLabelResponse model constructor.
     * @property {module:model/ShowMQTTLabelResponse}
     */
    ShowMQTTLabelResponse,

    /**
     * The SourceCode model constructor.
     * @property {module:model/SourceCode}
     */
    SourceCode,

    /**
     * The ThingCreateResponse model constructor.
     * @property {module:model/ThingCreateResponse}
     */
    ThingCreateResponse,

    /**
     * The ThingCreateResponseCredentials model constructor.
     * @property {module:model/ThingCreateResponseCredentials}
     */
    ThingCreateResponseCredentials,

    /**
     * The ThingCreateResponseCredentialsHttp model constructor.
     * @property {module:model/ThingCreateResponseCredentialsHttp}
     */
    ThingCreateResponseCredentialsHttp,

    /**
     * The ThingCreateResponseCredentialsMqtt model constructor.
     * @property {module:model/ThingCreateResponseCredentialsMqtt}
     */
    ThingCreateResponseCredentialsMqtt,

    /**
     * The ThingCreateResponseCredentialsMqttData model constructor.
     * @property {module:model/ThingCreateResponseCredentialsMqttData}
     */
    ThingCreateResponseCredentialsMqttData,

    /**
     * The ThingCreateResponseCredentialsMqttThing model constructor.
     * @property {module:model/ThingCreateResponseCredentialsMqttThing}
     */
    ThingCreateResponseCredentialsMqttThing,

    /**
     * The ThingCreateResponseLinks model constructor.
     * @property {module:model/ThingCreateResponseLinks}
     */
    ThingCreateResponseLinks,

    /**
     * The ThingDeleteResponse model constructor.
     * @property {module:model/ThingDeleteResponse}
     */
    ThingDeleteResponse,

    /**
     * The ThingDeleteResponseErrorClusterBackend model constructor.
     * @property {module:model/ThingDeleteResponseErrorClusterBackend}
     */
    ThingDeleteResponseErrorClusterBackend,

    /**
     * The ThingListResponse model constructor.
     * @property {module:model/ThingListResponse}
     */
    ThingListResponse,

    /**
     * The ThingRequest model constructor.
     * @property {module:model/ThingRequest}
     */
    ThingRequest,

    /**
     * The ThingResponse model constructor.
     * @property {module:model/ThingResponse}
     */
    ThingResponse,

    /**
     * The ThingStatusListResponse model constructor.
     * @property {module:model/ThingStatusListResponse}
     */
    ThingStatusListResponse,

    /**
     * The ThingStatusResponse model constructor.
     * @property {module:model/ThingStatusResponse}
     */
    ThingStatusResponse,

    /**
     * The ThingUpdateRequest model constructor.
     * @property {module:model/ThingUpdateRequest}
     */
    ThingUpdateRequest,

    /**
     * The ThingUpdateResponse model constructor.
     * @property {module:model/ThingUpdateResponse}
     */
    ThingUpdateResponse,

    /**
     * The TokenResponse model constructor.
     * @property {module:model/TokenResponse}
     */
    TokenResponse,

    /**
     * The Trigger model constructor.
     * @property {module:model/Trigger}
     */
    Trigger,

    /**
     * The TriggerMqttConfig model constructor.
     * @property {module:model/TriggerMqttConfig}
     */
    TriggerMqttConfig,

    /**
     * The TriggerRabbitMQConfig model constructor.
     * @property {module:model/TriggerRabbitMQConfig}
     */
    TriggerRabbitMQConfig,

    /**
     * The TriggerStatusEnum model constructor.
     * @property {module:model/TriggerStatusEnum}
     */
    TriggerStatusEnum,

    /**
     * The TriggerTypeEnum model constructor.
     * @property {module:model/TriggerTypeEnum}
     */
    TriggerTypeEnum,

    /**
     * The Triggers model constructor.
     * @property {module:model/Triggers}
     */
    Triggers,

    /**
     * The UpdateMQTTCredentials model constructor.
     * @property {module:model/UpdateMQTTCredentials}
     */
    UpdateMQTTCredentials,

    /**
     * The UpdateMQTTCredentialsResponse model constructor.
     * @property {module:model/UpdateMQTTCredentialsResponse}
     */
    UpdateMQTTCredentialsResponse,

    /**
     * The UpdateMQTTLabelCredentials model constructor.
     * @property {module:model/UpdateMQTTLabelCredentials}
     */
    UpdateMQTTLabelCredentials,

    /**
     * The UpdateMQTTPassword model constructor.
     * @property {module:model/UpdateMQTTPassword}
     */
    UpdateMQTTPassword,

    /**
    * The ActionsApi service constructor.
    * @property {module:api/ActionsApi}
    */
    ActionsApi,

    /**
    * The CollectionsApi service constructor.
    * @property {module:api/CollectionsApi}
    */
    CollectionsApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The FunctionsApi service constructor.
    * @property {module:api/FunctionsApi}
    */
    FunctionsApi,

    /**
    * The ItemsApi service constructor.
    * @property {module:api/ItemsApi}
    */
    ItemsApi,

    /**
    * The LabelApi service constructor.
    * @property {module:api/LabelApi}
    */
    LabelApi,

    /**
    * The LabeledEntitiesApi service constructor.
    * @property {module:api/LabeledEntitiesApi}
    */
    LabeledEntitiesApi,

    /**
    * The MQTTCredentialsApi service constructor.
    * @property {module:api/MQTTCredentialsApi}
    */
    MQTTCredentialsApi,

    /**
    * The MQTTLabelsApi service constructor.
    * @property {module:api/MQTTLabelsApi}
    */
    MQTTLabelsApi,

    /**
    * The MQTTThingsApi service constructor.
    * @property {module:api/MQTTThingsApi}
    */
    MQTTThingsApi,

    /**
    * The MQTTUsernameApi service constructor.
    * @property {module:api/MQTTUsernameApi}
    */
    MQTTUsernameApi,

    /**
    * The ModelVersionsApi service constructor.
    * @property {module:api/ModelVersionsApi}
    */
    ModelVersionsApi,

    /**
    * The ModelsApi service constructor.
    * @property {module:api/ModelsApi}
    */
    ModelsApi,

    /**
    * The OAuthApi service constructor.
    * @property {module:api/OAuthApi}
    */
    OAuthApi,

    /**
    * The PropertiesApi service constructor.
    * @property {module:api/PropertiesApi}
    */
    PropertiesApi,

    /**
    * The ThingsApi service constructor.
    * @property {module:api/ThingsApi}
    */
    ThingsApi,

    /**
    * The TriggersApi service constructor.
    * @property {module:api/TriggersApi}
    */
    TriggersApi
};
