/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionResponseElement1 from './ActionResponseElement1';

/**
 * The ActionDelayListResponse model module.
 * @module model/ActionDelayListResponse
 * @version 0.8.12
 */
class ActionDelayListResponse {
    /**
     * Constructs a new <code>ActionDelayListResponse</code>.
     * @alias module:model/ActionDelayListResponse
     */
    constructor() { 
        
        ActionDelayListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDelayListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDelayListResponse} obj Optional instance to populate.
     * @return {module:model/ActionDelayListResponse} The populated <code>ActionDelayListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDelayListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ActionResponseElement1]);
            }
            if (data.hasOwnProperty('paging')) {
                obj['paging'] = ApiClient.convertToType(data['paging'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ActionResponseElement1>} data
 */
ActionDelayListResponse.prototype['data'] = undefined;

/**
 * @member {Object} paging
 */
ActionDelayListResponse.prototype['paging'] = undefined;






export default ActionDelayListResponse;

