/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionRequestDelayInput model module.
 * @module model/ActionRequestDelayInput
 * @version 1.0.0
 */
class ActionRequestDelayInput {
    /**
     * Constructs a new <code>ActionRequestDelayInput</code>.
     * @alias module:model/ActionRequestDelayInput
     */
    constructor() { 
        
        ActionRequestDelayInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionRequestDelayInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionRequestDelayInput} obj Optional instance to populate.
     * @return {module:model/ActionRequestDelayInput} The populated <code>ActionRequestDelayInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionRequestDelayInput();

            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} delay
 */
ActionRequestDelayInput.prototype['delay'] = undefined;






export default ActionRequestDelayInput;

