/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionRequestDelayInput from './ActionRequestDelayInput';

/**
 * The ActionResponseElement1Delay model module.
 * @module model/ActionResponseElement1Delay
 * @version 1.0.0
 */
class ActionResponseElement1Delay {
    /**
     * Constructs a new <code>ActionResponseElement1Delay</code>.
     * @alias module:model/ActionResponseElement1Delay
     */
    constructor() { 
        
        ActionResponseElement1Delay.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionResponseElement1Delay</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionResponseElement1Delay} obj Optional instance to populate.
     * @return {module:model/ActionResponseElement1Delay} The populated <code>ActionResponseElement1Delay</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionResponseElement1Delay();

            if (data.hasOwnProperty('input')) {
                obj['input'] = ActionRequestDelayInput.constructFromObject(data['input']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('timeRequested')) {
                obj['timeRequested'] = ApiClient.convertToType(data['timeRequested'], 'Date');
            }
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ActionRequestDelayInput} input
 */
ActionResponseElement1Delay.prototype['input'] = undefined;

/**
 * @member {String} status
 */
ActionResponseElement1Delay.prototype['status'] = undefined;

/**
 * @member {Date} timeRequested
 */
ActionResponseElement1Delay.prototype['timeRequested'] = undefined;

/**
 * @member {String} href
 */
ActionResponseElement1Delay.prototype['href'] = undefined;






export default ActionResponseElement1Delay;

