/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionReboot model module.
 * @module model/ActionReboot
 * @version 1.0.0
 */
class ActionReboot {
    /**
     * Constructs a new <code>ActionReboot</code>.
     * @alias module:model/ActionReboot
     */
    constructor() { 
        
        ActionReboot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionReboot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionReboot} obj Optional instance to populate.
     * @return {module:model/ActionReboot} The populated <code>ActionReboot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionReboot();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
ActionReboot.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ActionReboot.prototype['description'] = undefined;






export default ActionReboot;

