/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionRequestDelay from './ActionRequestDelay';

/**
 * The ActionRequest model module.
 * @module model/ActionRequest
 * @version 1.0.0
 */
class ActionRequest {
    /**
     * Constructs a new <code>ActionRequest</code>.
     * @alias module:model/ActionRequest
     * @extends Object
     */
    constructor() { 
        
        ActionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionRequest} obj Optional instance to populate.
     * @return {module:model/ActionRequest} The populated <code>ActionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ActionRequestDelay.constructFromObject(data['delay']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ActionRequestDelay} delay
 */
ActionRequest.prototype['delay'] = undefined;






export default ActionRequest;

