/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthZErrorError model module.
 * @module model/AuthZErrorError
 * @version 1.0.0
 */
class AuthZErrorError {
    /**
     * Constructs a new <code>AuthZErrorError</code>.
     * @alias module:model/AuthZErrorError
     */
    constructor() { 
        
        AuthZErrorError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthZErrorError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthZErrorError} obj Optional instance to populate.
     * @return {module:model/AuthZErrorError} The populated <code>AuthZErrorError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthZErrorError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
AuthZErrorError.prototype['code'] = undefined;

/**
 * @member {String} message
 */
AuthZErrorError.prototype['message'] = undefined;

/**
 * @member {String} reason
 */
AuthZErrorError.prototype['reason'] = undefined;

/**
 * @member {String} status
 */
AuthZErrorError.prototype['status'] = undefined;






export default AuthZErrorError;

