/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BadFormedErrorError model module.
 * @module model/BadFormedErrorError
 * @version 1.0.0
 */
class BadFormedErrorError {
    /**
     * Constructs a new <code>BadFormedErrorError</code>.
     * @alias module:model/BadFormedErrorError
     */
    constructor() { 
        
        BadFormedErrorError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BadFormedErrorError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BadFormedErrorError} obj Optional instance to populate.
     * @return {module:model/BadFormedErrorError} The populated <code>BadFormedErrorError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BadFormedErrorError();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
BadFormedErrorError.prototype['message'] = undefined;

/**
 * @member {Number} status
 */
BadFormedErrorError.prototype['status'] = undefined;






export default BadFormedErrorError;

