/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionResponse from './CollectionResponse';

/**
 * The CollectionListResponse model module.
 * @module model/CollectionListResponse
 * @version 1.0.0
 */
class CollectionListResponse {
    /**
     * Constructs a new <code>CollectionListResponse</code>.
     * @alias module:model/CollectionListResponse
     */
    constructor() { 
        
        CollectionListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CollectionListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CollectionListResponse} obj Optional instance to populate.
     * @return {module:model/CollectionListResponse} The populated <code>CollectionListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [CollectionResponse]);
            }
            if (data.hasOwnProperty('paging')) {
                obj['paging'] = ApiClient.convertToType(data['paging'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/CollectionResponse>} data
 */
CollectionListResponse.prototype['data'] = undefined;

/**
 * @member {Object} paging
 */
CollectionListResponse.prototype['paging'] = undefined;






export default CollectionListResponse;

