/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CollectionUpdateRequest model module.
 * @module model/CollectionUpdateRequest
 * @version 0.8.12
 */
class CollectionUpdateRequest {
    /**
     * Constructs a new <code>CollectionUpdateRequest</code>.
     * @alias module:model/CollectionUpdateRequest
     */
    constructor() { 
        
        CollectionUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CollectionUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CollectionUpdateRequest} obj Optional instance to populate.
     * @return {module:model/CollectionUpdateRequest} The populated <code>CollectionUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionUpdateRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
CollectionUpdateRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
CollectionUpdateRequest.prototype['description'] = undefined;






export default CollectionUpdateRequest;

