/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateMQTTLabelCredentials model module.
 * @module model/CreateMQTTLabelCredentials
 * @version 1.0.0
 */
class CreateMQTTLabelCredentials {
    /**
     * Constructs a new <code>CreateMQTTLabelCredentials</code>.
     * @alias module:model/CreateMQTTLabelCredentials
     */
    constructor() { 
        
        CreateMQTTLabelCredentials.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateMQTTLabelCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateMQTTLabelCredentials} obj Optional instance to populate.
     * @return {module:model/CreateMQTTLabelCredentials} The populated <code>CreateMQTTLabelCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateMQTTLabelCredentials();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} label
 */
CreateMQTTLabelCredentials.prototype['label'] = undefined;

/**
 * @member {String} username
 */
CreateMQTTLabelCredentials.prototype['username'] = undefined;

/**
 * @member {String} password
 */
CreateMQTTLabelCredentials.prototype['password'] = undefined;






export default CreateMQTTLabelCredentials;

