/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateLabelResponse model module.
 * @module model/CreateLabelResponse
 * @version 1.0.0
 */
class CreateLabelResponse {
    /**
     * Constructs a new <code>CreateLabelResponse</code>.
     * @alias module:model/CreateLabelResponse
     */
    constructor() { 
        
        CreateLabelResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateLabelResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLabelResponse} obj Optional instance to populate.
     * @return {module:model/CreateLabelResponse} The populated <code>CreateLabelResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLabelResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ApiClient.convertToType(data['space'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('label_description')) {
                obj['label_description'] = ApiClient.convertToType(data['label_description'], 'String');
            }
            if (data.hasOwnProperty('label_name')) {
                obj['label_name'] = ApiClient.convertToType(data['label_name'], 'String');
            }
            if (data.hasOwnProperty('mqtt')) {
                obj['mqtt'] = ApiClient.convertToType(data['mqtt'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CreateLabelResponse.prototype['id'] = undefined;

/**
 * @member {String} space
 */
CreateLabelResponse.prototype['space'] = undefined;

/**
 * @member {String} color
 */
CreateLabelResponse.prototype['color'] = undefined;

/**
 * @member {String} label_description
 */
CreateLabelResponse.prototype['label_description'] = undefined;

/**
 * @member {String} label_name
 */
CreateLabelResponse.prototype['label_name'] = undefined;

/**
 * @member {Boolean} mqtt
 */
CreateLabelResponse.prototype['mqtt'] = undefined;






export default CreateLabelResponse;

