/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateLabel model module.
 * @module model/CreateLabel
 * @version 1.0.0
 */
class CreateLabel {
    /**
     * Constructs a new <code>CreateLabel</code>.
     * @alias module:model/CreateLabel
     */
    constructor() { 
        
        CreateLabel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateLabel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLabel} obj Optional instance to populate.
     * @return {module:model/CreateLabel} The populated <code>CreateLabel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLabel();

            if (data.hasOwnProperty('label_name')) {
                obj['label_name'] = ApiClient.convertToType(data['label_name'], 'String');
            }
            if (data.hasOwnProperty('label_description')) {
                obj['label_description'] = ApiClient.convertToType(data['label_description'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} label_name
 */
CreateLabel.prototype['label_name'] = undefined;

/**
 * @member {String} label_description
 */
CreateLabel.prototype['label_description'] = undefined;

/**
 * @member {String} color
 */
CreateLabel.prototype['color'] = undefined;






export default CreateLabel;

