/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventResponseHighCPU from './EventResponseHighCPU';

/**
 * The EventResponse model module.
 * @module model/EventResponse
 * @version 1.0.0
 */
class EventResponse {
    /**
     * Constructs a new <code>EventResponse</code>.
     * @alias module:model/EventResponse
     * @extends Object
     */
    constructor() { 
        
        EventResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventResponse} obj Optional instance to populate.
     * @return {module:model/EventResponse} The populated <code>EventResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventResponse();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('highCPU')) {
                obj['highCPU'] = EventResponseHighCPU.constructFromObject(data['highCPU']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/EventResponseHighCPU} highCPU
 */
EventResponse.prototype['highCPU'] = undefined;






export default EventResponse;

