/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventHighCPUData from './EventHighCPUData';
import PropertyCPUResponseLinks from './PropertyCPUResponseLinks';

/**
 * The EventHighCPUResponse model module.
 * @module model/EventHighCPUResponse
 * @version 1.0.0
 */
class EventHighCPUResponse {
    /**
     * Constructs a new <code>EventHighCPUResponse</code>.
     * @alias module:model/EventHighCPUResponse
     */
    constructor() { 
        
        EventHighCPUResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventHighCPUResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventHighCPUResponse} obj Optional instance to populate.
     * @return {module:model/EventHighCPUResponse} The populated <code>EventHighCPUResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventHighCPUResponse();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = EventHighCPUData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [PropertyCPUResponseLinks]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
EventHighCPUResponse.prototype['title'] = undefined;

/**
 * @member {String} description
 */
EventHighCPUResponse.prototype['description'] = undefined;

/**
 * @member {module:model/EventHighCPUData} data
 */
EventHighCPUResponse.prototype['data'] = undefined;

/**
 * @member {Array.<module:model/PropertyCPUResponseLinks>} links
 */
EventHighCPUResponse.prototype['links'] = undefined;






export default EventHighCPUResponse;

