/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Function from './Function';
import FunctionsPaging from './FunctionsPaging';

/**
 * The Functions model module.
 * @module model/Functions
 * @version 1.0.0
 */
class Functions {
    /**
     * Constructs a new <code>Functions</code>.
     * @alias module:model/Functions
     */
    constructor() { 
        
        Functions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Functions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Functions} obj Optional instance to populate.
     * @return {module:model/Functions} The populated <code>Functions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Functions();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Function]);
            }
            if (data.hasOwnProperty('paging')) {
                obj['paging'] = FunctionsPaging.constructFromObject(data['paging']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Function>} data
 */
Functions.prototype['data'] = undefined;

/**
 * @member {module:model/FunctionsPaging} paging
 */
Functions.prototype['paging'] = undefined;






export default Functions;

