/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FunctionOptions model module.
 * @module model/FunctionOptions
 * @version 1.0.0
 */
class FunctionOptions {
    /**
     * Constructs a new <code>FunctionOptions</code>.
     * @alias module:model/FunctionOptions
     */
    constructor() { 
        
        FunctionOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FunctionOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FunctionOptions} obj Optional instance to populate.
     * @return {module:model/FunctionOptions} The populated <code>FunctionOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FunctionOptions();

            if (data.hasOwnProperty('topics')) {
                obj['topics'] = ApiClient.convertToType(data['topics'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Comma-separated list of topics (see Triggers).
 * @member {String} topics
 */
FunctionOptions.prototype['topics'] = undefined;

/**
 * Cron format string to schedule function invocations (see cron trigger).
 * @member {String} schedule
 */
FunctionOptions.prototype['schedule'] = undefined;






export default FunctionOptions;

