/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FunctionMetrics from './FunctionMetrics';
import FunctionOptions from './FunctionOptions';
import FunctionStatusEnum from './FunctionStatusEnum';
import SourceCode from './SourceCode';

/**
 * The Function model module.
 * @module model/Function
 * @version 1.0.0
 */
class Function {
    /**
     * Constructs a new <code>Function</code>.
     * @alias module:model/Function
     */
    constructor() { 
        
        Function.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Function</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Function} obj Optional instance to populate.
     * @return {module:model/Function} The populated <code>Function</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Function();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ApiClient.convertToType(data['space'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('env')) {
                obj['env'] = ApiClient.convertToType(data['env'], Object);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = FunctionOptions.constructFromObject(data['options']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = SourceCode.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = FunctionStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = FunctionMetrics.constructFromObject(data['metrics']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Function.prototype['id'] = undefined;

/**
 * @member {String} space
 */
Function.prototype['space'] = undefined;

/**
 * Function name. Must be unique and can only contain lowercase letters, numbers and hyphens.
 * @member {String} name
 */
Function.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Function.prototype['description'] = undefined;

/**
 * @member {String} template
 */
Function.prototype['template'] = undefined;

/**
 * Environment variables used by the function. All values must be strings.
 * @member {Object} env
 */
Function.prototype['env'] = undefined;

/**
 * @member {module:model/FunctionOptions} options
 */
Function.prototype['options'] = undefined;

/**
 * @member {module:model/SourceCode} source
 */
Function.prototype['source'] = undefined;

/**
 * @member {module:model/FunctionStatusEnum} status
 */
Function.prototype['status'] = undefined;

/**
 * @member {module:model/FunctionMetrics} metrics
 */
Function.prototype['metrics'] = undefined;

/**
 * @member {String} created_at
 */
Function.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
Function.prototype['updated_at'] = undefined;






export default Function;

