/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FunctionsPaging model module.
 * @module model/FunctionsPaging
 * @version 1.0.0
 */
class FunctionsPaging {
    /**
     * Constructs a new <code>FunctionsPaging</code>.
     * @alias module:model/FunctionsPaging
     */
    constructor() { 
        
        FunctionsPaging.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FunctionsPaging</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FunctionsPaging} obj Optional instance to populate.
     * @return {module:model/FunctionsPaging} The populated <code>FunctionsPaging</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FunctionsPaging();

            if (data.hasOwnProperty('next_cursor')) {
                obj['next_cursor'] = ApiClient.convertToType(data['next_cursor'], 'String');
            }
            if (data.hasOwnProperty('previous_cursor')) {
                obj['previous_cursor'] = ApiClient.convertToType(data['previous_cursor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} next_cursor
 */
FunctionsPaging.prototype['next_cursor'] = undefined;

/**
 * @member {String} previous_cursor
 */
FunctionsPaging.prototype['previous_cursor'] = undefined;






export default FunctionsPaging;

