/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabeledListItem1 model module.
 * @module model/LabeledListItem1
 * @version 1.0.0
 */
class LabeledListItem1 {
    /**
     * Constructs a new <code>LabeledListItem1</code>.
     * @alias module:model/LabeledListItem1
     */
    constructor() { 
        
        LabeledListItem1.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LabeledListItem1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LabeledListItem1} obj Optional instance to populate.
     * @return {module:model/LabeledListItem1} The populated <code>LabeledListItem1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabeledListItem1();

            if (data.hasOwnProperty('entity_id')) {
                obj['entity_id'] = ApiClient.convertToType(data['entity_id'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], Array);
            }
        }
        return obj;
    }


}

/**
 * @member {String} entity_id
 */
LabeledListItem1.prototype['entity_id'] = undefined;

/**
 * @member {Array} labels
 */
LabeledListItem1.prototype['labels'] = undefined;






export default LabeledListItem1;

