/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelVersionResponseAllOf model module.
 * @module model/ModelVersionResponseAllOf
 * @version 1.0.0
 */
class ModelVersionResponseAllOf {
    /**
     * Constructs a new <code>ModelVersionResponseAllOf</code>.
     * @alias module:model/ModelVersionResponseAllOf
     */
    constructor() { 
        
        ModelVersionResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelVersionResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelVersionResponseAllOf} obj Optional instance to populate.
     * @return {module:model/ModelVersionResponseAllOf} The populated <code>ModelVersionResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelVersionResponseAllOf();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} version
 */
ModelVersionResponseAllOf.prototype['version'] = undefined;






export default ModelVersionResponseAllOf;

