/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelVersionRequest from './ModelVersionRequest';

/**
 * The ModelVersionResponse model module.
 * @module model/ModelVersionResponse
 * @version 0.8.12
 */
class ModelVersionResponse {
    /**
     * Constructs a new <code>ModelVersionResponse</code>.
     * @alias module:model/ModelVersionResponse
     */
    constructor() { 
        
        ModelVersionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelVersionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelVersionResponse} obj Optional instance to populate.
     * @return {module:model/ModelVersionResponse} The populated <code>ModelVersionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelVersionResponse();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ModelVersionRequest.constructFromObject(data['template']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} version
 */
ModelVersionResponse.prototype['version'] = undefined;

/**
 * @member {module:model/ModelVersionRequest} template
 */
ModelVersionResponse.prototype['template'] = undefined;






export default ModelVersionResponse;

