/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyCPUResponseLinks from './PropertyCPUResponseLinks';

/**
 * The PropertyMemoryResponse model module.
 * @module model/PropertyMemoryResponse
 * @version 1.0.0
 */
class PropertyMemoryResponse {
    /**
     * Constructs a new <code>PropertyMemoryResponse</code>.
     * @alias module:model/PropertyMemoryResponse
     */
    constructor() { 
        
        PropertyMemoryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyMemoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyMemoryResponse} obj Optional instance to populate.
     * @return {module:model/PropertyMemoryResponse} The populated <code>PropertyMemoryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyMemoryResponse();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [PropertyCPUResponseLinks]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
PropertyMemoryResponse.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PropertyMemoryResponse.prototype['description'] = undefined;

/**
 * @member {String} type
 */
PropertyMemoryResponse.prototype['type'] = undefined;

/**
 * @member {String} unit
 */
PropertyMemoryResponse.prototype['unit'] = undefined;

/**
 * @member {Boolean} readOnly
 */
PropertyMemoryResponse.prototype['readOnly'] = undefined;

/**
 * @member {Array.<module:model/PropertyCPUResponseLinks>} links
 */
PropertyMemoryResponse.prototype['links'] = undefined;






export default PropertyMemoryResponse;

