/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Properties model module.
 * @module model/Properties
 * @version 1.0.0
 */
class Properties {
    /**
     * Constructs a new <code>Properties</code>.
     * @alias module:model/Properties
     */
    constructor() { 
        
        Properties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Properties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Properties} obj Optional instance to populate.
     * @return {module:model/Properties} The populated <code>Properties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Properties();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = ApiClient.convertToType(data['cpu'], 'Number');
            }
            if (data.hasOwnProperty('disk')) {
                obj['disk'] = ApiClient.convertToType(data['disk'], 'Number');
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cpu
 */
Properties.prototype['cpu'] = undefined;

/**
 * @member {Number} disk
 */
Properties.prototype['disk'] = undefined;

/**
 * @member {Number} memory
 */
Properties.prototype['memory'] = undefined;






export default Properties;

