/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelationErrorError from './RelationErrorError';

/**
 * The RelationError model module.
 * @module model/RelationError
 * @version 1.0.0
 */
class RelationError {
    /**
     * Constructs a new <code>RelationError</code>.
     * @alias module:model/RelationError
     */
    constructor() { 
        
        RelationError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RelationError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelationError} obj Optional instance to populate.
     * @return {module:model/RelationError} The populated <code>RelationError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelationError();

            if (data.hasOwnProperty('error')) {
                obj['error'] = RelationErrorError.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RelationErrorError} error
 */
RelationError.prototype['error'] = undefined;






export default RelationError;

