/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MQTTLabel from './MQTTLabel';

/**
 * The ShowMQTTLabelResponse model module.
 * @module model/ShowMQTTLabelResponse
 * @version 1.0.0
 */
class ShowMQTTLabelResponse {
    /**
     * Constructs a new <code>ShowMQTTLabelResponse</code>.
     * @alias module:model/ShowMQTTLabelResponse
     */
    constructor() { 
        
        ShowMQTTLabelResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShowMQTTLabelResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShowMQTTLabelResponse} obj Optional instance to populate.
     * @return {module:model/ShowMQTTLabelResponse} The populated <code>ShowMQTTLabelResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShowMQTTLabelResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('expired_at')) {
                obj['expired_at'] = ApiClient.convertToType(data['expired_at'], 'Number');
            }
            if (data.hasOwnProperty('topics')) {
                obj['topics'] = ApiClient.convertToType(data['topics'], [MQTTLabel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ShowMQTTLabelResponse.prototype['id'] = undefined;

/**
 * @member {String} description
 */
ShowMQTTLabelResponse.prototype['description'] = undefined;

/**
 * @member {String} type
 */
ShowMQTTLabelResponse.prototype['type'] = undefined;

/**
 * @member {String} username
 */
ShowMQTTLabelResponse.prototype['username'] = undefined;

/**
 * @member {Boolean} enabled
 */
ShowMQTTLabelResponse.prototype['enabled'] = undefined;

/**
 * @member {Date} created_at
 */
ShowMQTTLabelResponse.prototype['created_at'] = undefined;

/**
 * @member {Number} expired_at
 */
ShowMQTTLabelResponse.prototype['expired_at'] = undefined;

/**
 * @member {Array.<module:model/MQTTLabel>} topics
 */
ShowMQTTLabelResponse.prototype['topics'] = undefined;






export default ShowMQTTLabelResponse;

