/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Properties from './Properties';

/**
 * The ThingStatusResponse model module.
 * @module model/ThingStatusResponse
 * @version 1.0.0
 */
class ThingStatusResponse {
    /**
     * Constructs a new <code>ThingStatusResponse</code>.
     * @alias module:model/ThingStatusResponse
     */
    constructor() { 
        
        ThingStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingStatusResponse} obj Optional instance to populate.
     * @return {module:model/ThingStatusResponse} The populated <code>ThingStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingStatusResponse();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ApiClient.convertToType(data['space'], 'String');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = Properties.constructFromObject(data['properties']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} uid
 */
ThingStatusResponse.prototype['uid'] = undefined;

/**
 * @member {String} title
 */
ThingStatusResponse.prototype['title'] = undefined;

/**
 * @member {String} space
 */
ThingStatusResponse.prototype['space'] = undefined;

/**
 * @member {String} collection
 */
ThingStatusResponse.prototype['collection'] = undefined;

/**
 * @member {module:model/Properties} properties
 */
ThingStatusResponse.prototype['properties'] = undefined;






export default ThingStatusResponse;

