/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyCPUResponse from './PropertyCPUResponse';
import PropertyDiskResponse from './PropertyDiskResponse';
import PropertyMemoryResponse from './PropertyMemoryResponse';

/**
 * The ThingCreateResponseProperties model module.
 * @module model/ThingCreateResponseProperties
 * @version 0.8.12
 */
class ThingCreateResponseProperties {
    /**
     * Constructs a new <code>ThingCreateResponseProperties</code>.
     * @alias module:model/ThingCreateResponseProperties
     */
    constructor() { 
        
        ThingCreateResponseProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingCreateResponseProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingCreateResponseProperties} obj Optional instance to populate.
     * @return {module:model/ThingCreateResponseProperties} The populated <code>ThingCreateResponseProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingCreateResponseProperties();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = PropertyCPUResponse.constructFromObject(data['cpu']);
            }
            if (data.hasOwnProperty('disk')) {
                obj['disk'] = PropertyDiskResponse.constructFromObject(data['disk']);
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = PropertyMemoryResponse.constructFromObject(data['memory']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PropertyCPUResponse} cpu
 */
ThingCreateResponseProperties.prototype['cpu'] = undefined;

/**
 * @member {module:model/PropertyDiskResponse} disk
 */
ThingCreateResponseProperties.prototype['disk'] = undefined;

/**
 * @member {module:model/PropertyMemoryResponse} memory
 */
ThingCreateResponseProperties.prototype['memory'] = undefined;






export default ThingCreateResponseProperties;

