/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionDelay from './ActionDelay';
import ActionReboot from './ActionReboot';

/**
 * The ThingRequestActions model module.
 * @module model/ThingRequestActions
 * @version 1.0.0
 */
class ThingRequestActions {
    /**
     * Constructs a new <code>ThingRequestActions</code>.
     * @alias module:model/ThingRequestActions
     */
    constructor() { 
        
        ThingRequestActions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingRequestActions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingRequestActions} obj Optional instance to populate.
     * @return {module:model/ThingRequestActions} The populated <code>ThingRequestActions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingRequestActions();

            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ActionDelay.constructFromObject(data['delay']);
            }
            if (data.hasOwnProperty('reboot')) {
                obj['reboot'] = ActionReboot.constructFromObject(data['reboot']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ActionDelay} delay
 */
ThingRequestActions.prototype['delay'] = undefined;

/**
 * @member {module:model/ActionReboot} reboot
 */
ThingRequestActions.prototype['reboot'] = undefined;






export default ThingRequestActions;

