/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ThingCreateResponseCredentialsHttp model module.
 * @module model/ThingCreateResponseCredentialsHttp
 * @version 1.0.0
 */
class ThingCreateResponseCredentialsHttp {
    /**
     * Constructs a new <code>ThingCreateResponseCredentialsHttp</code>.
     * @alias module:model/ThingCreateResponseCredentialsHttp
     */
    constructor() { 
        
        ThingCreateResponseCredentialsHttp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingCreateResponseCredentialsHttp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingCreateResponseCredentialsHttp} obj Optional instance to populate.
     * @return {module:model/ThingCreateResponseCredentialsHttp} The populated <code>ThingCreateResponseCredentialsHttp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingCreateResponseCredentialsHttp();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
ThingCreateResponseCredentialsHttp.prototype['client_id'] = undefined;

/**
 * @member {String} client_secret
 */
ThingCreateResponseCredentialsHttp.prototype['client_secret'] = undefined;






export default ThingCreateResponseCredentialsHttp;

