/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ThingCreateResponseCredentialsMqttData model module.
 * @module model/ThingCreateResponseCredentialsMqttData
 * @version 0.8.12
 */
class ThingCreateResponseCredentialsMqttData {
    /**
     * Constructs a new <code>ThingCreateResponseCredentialsMqttData</code>.
     * @alias module:model/ThingCreateResponseCredentialsMqttData
     */
    constructor() { 
        
        ThingCreateResponseCredentialsMqttData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingCreateResponseCredentialsMqttData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingCreateResponseCredentialsMqttData} obj Optional instance to populate.
     * @return {module:model/ThingCreateResponseCredentialsMqttData} The populated <code>ThingCreateResponseCredentialsMqttData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingCreateResponseCredentialsMqttData();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('pwd')) {
                obj['pwd'] = ApiClient.convertToType(data['pwd'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
ThingCreateResponseCredentialsMqttData.prototype['username'] = undefined;

/**
 * @member {String} pwd
 */
ThingCreateResponseCredentialsMqttData.prototype['pwd'] = undefined;






export default ThingCreateResponseCredentialsMqttData;

