/**
 * Digital Model API (WIP)
 * Digital Model API documentation
 *
 * The version of the OpenAPI document: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventHighCPU from './EventHighCPU';

/**
 * The ThingRequestEvents model module.
 * @module model/ThingRequestEvents
 * @version 0.8.12
 */
class ThingRequestEvents {
    /**
     * Constructs a new <code>ThingRequestEvents</code>.
     * @alias module:model/ThingRequestEvents
     */
    constructor() { 
        
        ThingRequestEvents.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingRequestEvents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingRequestEvents} obj Optional instance to populate.
     * @return {module:model/ThingRequestEvents} The populated <code>ThingRequestEvents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingRequestEvents();

            if (data.hasOwnProperty('highCPU')) {
                obj['highCPU'] = EventHighCPU.constructFromObject(data['highCPU']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/EventHighCPU} highCPU
 */
ThingRequestEvents.prototype['highCPU'] = undefined;






export default ThingRequestEvents;

