/**
 * MQTT API reference
 * MQTT OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ThingCreateResponseLinks model module.
 * @module model/ThingCreateResponseLinks
 * @version 1.0.0
 */
class ThingCreateResponseLinks {
    /**
     * Constructs a new <code>ThingCreateResponseLinks</code>.
     * @alias module:model/ThingCreateResponseLinks
     */
    constructor() { 
        
        ThingCreateResponseLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingCreateResponseLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingCreateResponseLinks} obj Optional instance to populate.
     * @return {module:model/ThingCreateResponseLinks} The populated <code>ThingCreateResponseLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingCreateResponseLinks();

            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('rel')) {
                obj['rel'] = ApiClient.convertToType(data['rel'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} href
 */
ThingCreateResponseLinks.prototype['href'] = undefined;

/**
 * @member {String} rel
 */
ThingCreateResponseLinks.prototype['rel'] = undefined;






export default ThingCreateResponseLinks;

