/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ThingRequestActions from './ThingRequestActions';
import ThingRequestEvents from './ThingRequestEvents';
import ThingRequestProperties from './ThingRequestProperties';

/**
 * The ThingUpdateRequest model module.
 * @module model/ThingUpdateRequest
 * @version 1.0.0
 */
class ThingUpdateRequest {
    /**
     * Constructs a new <code>ThingUpdateRequest</code>.
     * @alias module:model/ThingUpdateRequest
     */
    constructor() { 
        
        ThingUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingUpdateRequest} obj Optional instance to populate.
     * @return {module:model/ThingUpdateRequest} The populated <code>ThingUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingUpdateRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ThingRequestProperties.constructFromObject(data['properties']);
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ThingRequestActions.constructFromObject(data['actions']);
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ThingRequestEvents.constructFromObject(data['events']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
ThingUpdateRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ThingUpdateRequest.prototype['description'] = undefined;

/**
 * @member {module:model/ThingRequestProperties} properties
 */
ThingUpdateRequest.prototype['properties'] = undefined;

/**
 * @member {module:model/ThingRequestActions} actions
 */
ThingUpdateRequest.prototype['actions'] = undefined;

/**
 * @member {module:model/ThingRequestEvents} events
 */
ThingUpdateRequest.prototype['events'] = undefined;






export default ThingUpdateRequest;

