/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyCPU from './PropertyCPU';
import PropertyDisk from './PropertyDisk';
import PropertyMemory from './PropertyMemory';

/**
 * The ThingRequestProperties model module.
 * @module model/ThingRequestProperties
 * @version 1.0.0
 */
class ThingRequestProperties {
    /**
     * Constructs a new <code>ThingRequestProperties</code>.
     * @alias module:model/ThingRequestProperties
     */
    constructor() { 
        
        ThingRequestProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingRequestProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingRequestProperties} obj Optional instance to populate.
     * @return {module:model/ThingRequestProperties} The populated <code>ThingRequestProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingRequestProperties();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = PropertyCPU.constructFromObject(data['cpu']);
            }
            if (data.hasOwnProperty('disk')) {
                obj['disk'] = PropertyDisk.constructFromObject(data['disk']);
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = PropertyMemory.constructFromObject(data['memory']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PropertyCPU} cpu
 */
ThingRequestProperties.prototype['cpu'] = undefined;

/**
 * @member {module:model/PropertyDisk} disk
 */
ThingRequestProperties.prototype['disk'] = undefined;

/**
 * @member {module:model/PropertyMemory} memory
 */
ThingRequestProperties.prototype['memory'] = undefined;






export default ThingRequestProperties;

