/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ThingCreateResponseLinks from './ThingCreateResponseLinks';

/**
 * The ThingUpdateResponse model module.
 * @module model/ThingUpdateResponse
 * @version 1.0.0
 */
class ThingUpdateResponse {
    /**
     * Constructs a new <code>ThingUpdateResponse</code>.
     * @alias module:model/ThingUpdateResponse
     */
    constructor() { 
        
        ThingUpdateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingUpdateResponse} obj Optional instance to populate.
     * @return {module:model/ThingUpdateResponse} The populated <code>ThingUpdateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingUpdateResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ApiClient.convertToType(data['space'], 'String');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], {'String': Object});
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': Object});
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], {'String': Object});
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], {'String': Object});
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [ThingCreateResponseLinks]);
            }
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ThingUpdateResponse.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
ThingUpdateResponse.prototype['uid'] = undefined;

/**
 * @member {String} title
 */
ThingUpdateResponse.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ThingUpdateResponse.prototype['description'] = undefined;

/**
 * @member {String} space
 */
ThingUpdateResponse.prototype['space'] = undefined;

/**
 * @member {String} collection
 */
ThingUpdateResponse.prototype['collection'] = undefined;

/**
 * @member {Object.<String, Object>} model
 */
ThingUpdateResponse.prototype['model'] = undefined;

/**
 * @member {Object.<String, Object>} properties
 */
ThingUpdateResponse.prototype['properties'] = undefined;

/**
 * @member {Object.<String, Object>} actions
 */
ThingUpdateResponse.prototype['actions'] = undefined;

/**
 * @member {Object.<String, Object>} events
 */
ThingUpdateResponse.prototype['events'] = undefined;

/**
 * @member {Array.<module:model/ThingCreateResponseLinks>} links
 */
ThingUpdateResponse.prototype['links'] = undefined;

/**
 * @member {String} href
 */
ThingUpdateResponse.prototype['href'] = undefined;

/**
 * @member {String} version
 */
ThingUpdateResponse.prototype['version'] = undefined;






export default ThingUpdateResponse;

