/**
 * Users API reference
 * Users OpenAPI endpoints - OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ThingCreateResponseCredentialsMqttThing model module.
 * @module model/ThingCreateResponseCredentialsMqttThing
 * @version 1.0.0
 */
class ThingCreateResponseCredentialsMqttThing {
    /**
     * Constructs a new <code>ThingCreateResponseCredentialsMqttThing</code>.
     * @alias module:model/ThingCreateResponseCredentialsMqttThing
     */
    constructor() { 
        
        ThingCreateResponseCredentialsMqttThing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThingCreateResponseCredentialsMqttThing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThingCreateResponseCredentialsMqttThing} obj Optional instance to populate.
     * @return {module:model/ThingCreateResponseCredentialsMqttThing} The populated <code>ThingCreateResponseCredentialsMqttThing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThingCreateResponseCredentialsMqttThing();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('pwd')) {
                obj['pwd'] = ApiClient.convertToType(data['pwd'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
ThingCreateResponseCredentialsMqttThing.prototype['username'] = undefined;

/**
 * @member {String} pwd
 */
ThingCreateResponseCredentialsMqttThing.prototype['pwd'] = undefined;






export default ThingCreateResponseCredentialsMqttThing;

