/**
 * SmartWorks SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FunctionsPaging from './FunctionsPaging';
import Trigger from './Trigger';

/**
 * The Triggers model module.
 * @module model/Triggers
 * @version 1.0.0
 */
class Triggers {
    /**
     * Constructs a new <code>Triggers</code>.
     * @alias module:model/Triggers
     */
    constructor() { 
        
        Triggers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Triggers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Triggers} obj Optional instance to populate.
     * @return {module:model/Triggers} The populated <code>Triggers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Triggers();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Trigger]);
            }
            if (data.hasOwnProperty('paging')) {
                obj['paging'] = FunctionsPaging.constructFromObject(data['paging']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Trigger>} data
 */
Triggers.prototype['data'] = undefined;

/**
 * @member {module:model/FunctionsPaging} paging
 */
Triggers.prototype['paging'] = undefined;






export default Triggers;

